apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.earlbot.name}}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    bot_token: {{ .Values.earlbot.encEnv.bot_token }}

  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.earlbot.name}}-secrets
      namespace: {{ .Release.Namespace }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.earlbot.name }}"
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.earlbot.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.earlbot.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.earlbot.name }}"
    spec:
      containers:
        - name: "{{ .Values.earlbot.name }}"
          image: "{{ .Values.earlbot.deployment.image }}:{{ .Values.earlbot.deployment.tag }}"
          env:
            {{- include "env.earlbot" . | indent 12 -}}
            # - name: BOT_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: secrets
            #       key: bot_token
            #       optional: false 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
 
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.earlbot.name }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
      app: "{{ .Values.earlbot.name }}"
  ports:
    - port: 8080
 

