version: "3.3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - '27017'
   

    # localstack:
    #     image: localstack/localstack
    #     ports:
    #         - "53:53"
    #         - "443:443"
    #         - "4510-4520:4510-4520"
    #         - "4566-4620:4566-4620"
    #         - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    #     environment:
    #         - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    #         - HOSTNAME_EXTERNAL=localstack
    #         - DEBUG=1
    #         - DATA_DIR=/tmp/localstack/data
    #         - DOCKER_HOST=unix:///var/run/docker.sock
    #         - LAMBDA_EXECUTOR=docker
    #         - LAMBDA_NETWORK=bridge
    #     volumes:
    #         - "/var/run/docker.sock:/var/run/docker.sock"
    #     tmpfs:
    #         - /tmp/localstack:exec,mode=600