apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: default
spec:
  encryptedData:
    bot_token: AgAswYj0cP38KZPen9lbGRj4gPBOA+io2wZ9CHLpty9R4he1vyUqwCXc0E/26/TWC3rdfsBQIaQv8vR307DpK90KzCUjcaPWdzvd7bzUL1ikUnkvAXuHieyw0dboKwrJsU+IlrVfOkf00sdeRmH42bDlaPLy+SBrLKQ/lMp8OSUqlHp0pEFYcob9tzH304Y9xwcSa0khj7yyK/y7+5tfcYswrc8ppJXe93pS5p/EDDP7jsUtEbaKo9kjhB+l/+wqIZdiNtFJ1SWISsrDo0YbRYrEV1b8IHjro/UNUkTPtiwveYuULkJASqyN4ulbbj8W1DPJrSyxn/ynP2zFzAJe7tTUMQDN+kh/GmnSNVhNKKRzg2YgVDAx6xPdo3Mnx3zoHBV8DKfFbh6jwuyndtPJNmgZfCwM4m9HdQFNw+njlPeBX6Ltekm1DuGpCiSaV7WkJ7E97o921bwCFBf/Sie8d7aDo5uQ2srjjussz+fnStjsMT9vI2MiwnK/BwQIAiRSgRkrdcUY0K3RP8+fUL/eEof+8JCeWZ1N1lwUNl2p/uPUf0zxTL1OlilFnxKCwG5RcxRpVrW6O2j4aD7A7mKAC0Rps64cE2robR8BNSfSf3+wWTxxjv0rMJ8CWan5KRUfBHFSvU6tbfM6ygf9NR4onsE6IbFHl2xQ2XeirxT1AA8yLD8wJS5Q4+Ejk/AeC2c/MLt8Bd2fU8DuV6vyHfZXimJh4bm2xOoFDzYnIgnO7l9w/EWT3uugXTwApg0eklVYSZV9/bA6kvhuKtZRgjGqMKQu+A596B3z3QEo
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: default

